---
layout: post
title:  "Barış En Güzel Hz. Mehdi (a.s.)'ın Şahsında Tecelli Edecektir"
author: jane
categories: [ Mehdi ]
tags: [makale]
keywords: Barış Güzel
image: assets/images/voice.jpeg
comments: false
published: true
lang: tr
encoding: UTF-8
---

Yüce Allah, Kuran-ı Kerim’de İslam ahlakını yeryüzüne hakim kılacağını İslam’ın hakim olmasıyla dünyaya barış, adalet ve sevginin geleceğini bildirmiştir. Peygamber Efendimiz (s.a.v.) de hadislerinde, bu büyük olayın ahir zamanda gerçekleşeceğini müjdelemiştir. Bu kutlu dönemde dünyanın her yerinde etnik ve siyasi sorunlar, iç savaşlar, çatışmalar, derin anlaşmazlıklar ve ihtilaflar son bulacaktır. Hadislerde ve İslam alimlerinin sözlerinde bildirildiğine göre İslam ahlakının dünyaya hakim olmasına ve barışa vesile olacak mübarek kişi ise, Hz. Mehdi (a.s.)’dır. Hz. Mehdi (a.s.)’ın ortaya çıkışıyla, Allah’ın izniyle, yeryüzündeki tüm zulüm ve haksızlıklar sona erecek; dünyaya adalet, barış, sevgi, huzur ve güven hakim olacaktır.

• Peygamber Efendimiz (s.a.v.) bu kutlu dönemi nasıl tarif etmektedir? • Sayın Adnan Oktar dünyaya barış ve adaletin hakim olacağını nasıl anlatmaktadır?

“Allah barış yurduna çağırır ve kimi dilerse dosdoğru yola yöneltip-iletir.” (Yunus Suresi, 25) ayetiyle Yüce Allah, mümin kullarına barışçı olmayı emretmekte ve insanları doğruya, gerçeğe, güzele götüren en parlak ışığın İslam olacağını müjdemektedir. Ancak 19. yüzyılın başlarından itibaren adaleti, merhameti, hoşgörüyü emreden Kuran ahlakının yerine, bir takım çarpık felsefe ve ideolojiler toplumlara benimsetilmeye başlanmıştır. Materyalist kökenli ideolojilerin, insanların nefislerindeki bencillik, dünya hırsı, sorumsuzluk, başkaldırı, isyankarlık gibi zaafları körüklemesiyle, toplumların bozulma süreci başlamıştır. Bu sapkın akımların yoğun telkin ve propagandaları sonucunda dünyada kargaşa ve bölünmeler yaşanmıştır.

Nitekim geride bıraktığımız 20. yüzyıl “Savaşlar Yüzyılı” olarak anılmaktadır. İçinde bulunduğumuz 21. yüzyıl da yine savaşlar ve terör olayları ile başlamıştır ve halen de bunlar dünyanın dört bir yanında devam etmektedir. Günümüzde hiçbir ülke terör saldırılarından yana güvende değildir. Avrupa’dan Amerika’ya, Asya’dan Afrika’ya kadar dünyanın dört bir yanında terörist bombalamalar, kundaklamalar, uçak kaçırmalar, rehin almalar, iç çatışmalar, masum ve sivil insanları hedef alan terörist saldırıların yanısıra günlük hayatta karşılaşılan bireysel şiddet olayları da büyük bir hızla devam etmektedir. Bugün ABD’den Angola, Uganda, Nijerya gibi Afrika ülkelerine; İngiltere, İspanya, Fransa gibi Avrupa ülkelerinden Sri Lanka, Tayland, Japonya gibi Asya ülkelerine; Ortadoğu ülkelerinden Latin Amerika’ya kadar birçok ülkede terör ve iç savaşlar binlerce insanın canını yakmakta ve çok büyük maddi kayıplara neden olmaktadır. İnsanlar şiddet olayları ve saldırılara evlerinde otururken, bir sinemada film izlerken, bir alışveriş merkezinde dolaşırken, otobüste yolculuk ederken ya da işyerlerinde çalışırken hiç beklemedikleri bir anda maruz kalmaktadırlar. Şiddetin evlerine kadar girmiş olması, doğal olarak insanlarda büyük bir tedirginlik, korku ve endişeli bir bekleyiş oluşturmaktadır. İnsanlar kalabalık ortamlara girmekten, toplu taşıma araçlarını kullanmaktan çekinmekte, günlük hayatlarını yaşayamaz hale gelmektedirler. Kısacası terörizm, savaşlar ve çatışmalar tüm dünyaya büyük yıkım getirmekte, insanların hayatları üzerinde çok olumsuz etkiler oluşturmaktadır. Peygamberimiz (s.a.v.), hadislerinde ahir zamanda yaşanacak bu ortamı şöyle tarif etmektedir: “... Sonunda da BELALAR, FİTNELER VE HOŞLANMAYACAĞINIZ BİRÇOK KÖTÜ İŞLER İSABET EDECEKTİR. Arka arkaya öyle fitneler gelir ki, sonra gelen gittikçe daha büyük olduğu için önce geleni ince ve hafif bırakır.” (İmam Şa’rani, Ölüm-Kıyamet-Ahiret ve Ahirzaman Alametleri, s. 394-395, no. 733)

Ancak yine Peygamberimiz (s.a.v.)’in müjdelerine göre, bu korku ve şiddet dolu karanlık dönemin ardından Yüce Allah Hz. Mehdi (a.s.) vesilesiyle tüm insanlığı büyük bir kurtuluşa ulaştıracaktır. Yeryüzündeki tüm fitneler, savaşlar, katliamlar, terör, şiddet ve anarşi eylemleri son bulacak; yerini aydınlık, barış ve huzur dolu bir döneme bırakacaktır. Hadislerde Hz. Mehdi (a.s.)’ın “fitneleri önleyeceği” şöyle bildirilmektedir:

“FİTNELERİ ÖNLEMENİN KENDİSİNE ZOR GELMEYECEĞİ VE ÖLDÜRMENİN DE ONU VAZGEÇİREMEYECEĞİ EHLİ BEYTİME MENSUP BİRİSİ SAHİP OLMADAN GÜNLER VE GECELER BİTMEYECEKTİR.” (Kitab-ül Burhan fi Alamet-il Mehdiyy-il Ahir Zaman, s. 12) “TOZLU, DUMANLI KARANLIK BİR FİTNE GÖRÜLECEK, BUNU DİĞERLERİ TAKİB EDECEK, TA Kİ EHLİ BEYTİMDEN KENDİSİNE MEHDİ DENİLEN BİR ZAT ÇIKINCAYA KADAR. Şayet ona yetişirsen, ona tabi ol ve hidayete erenlerden ol.” (Kitab-ül Burhan fi Alamet-il Mehdiyy-il Ahir Zaman, s. 26)
Hz. Mehdi (a.s.) Çatışmaları ve Anlaşmazlıkları Sona Erdirecektir

Yüce Allah’ın “Ey iman edenler, hepiniz topluca “barış ve güvenliğe (Silm’e, İslam’a) girin ve şeytanın adımlarını izlemeyin. Çünkü o, size apaçık bir düşmandır.” (Bakara Suresi, 208) ayetinde haber verdiği gibi Kuran ahlakının tüm dünyaya hakim olması sonucunda insanlar arasındaki kin, husumet, düşmanlık gibi duygular son bulacak, tüm yeryüzüne barış ve huzur hakim olacaktır. Hz. Mehdi (a.s.)’ın vesilesiyle, önceden aralarında husumet olan halklar arasında çok büyük bir kardeşlik yaşanacak, tüm sorunlar sevgi ve güzel ahlak ile çözüme kavuşturulacaktır. Peygamberimiz (s.a.v.) Hz. Mehdi (a.s.)’ın bu önemli özelliğini hadislerinde şöyle haber vermektedir:

“Kap su ile dolduğu gibi yeryüzü barışla dolacaktır. HİÇBİR KİMSE ARASINDA BİR DÜŞMANLIK KALMAYACAKTIR. VE BÜTÜN DÜŞMANLIKLAR, BOĞUŞMALAR, HASETLEŞMELER MUHAKKAK KAYBOLUP GİDECEKTİR.” (Sahih-i Müslim, 1/136) “SAVAŞ (ERBABI) DA AĞIRLIKLARINI (SİLAH VE MALZEMELERİNİ) BIRAKACAK.” (Sünen-i İbn Mace, 10/334) “HARP (ERBABİ) AĞIRLIKLARINI (YANİ SİLAH VE SAİREYİ) BIRAKIR.” (Ölüm-Kıyamet-Ahiret ve Ahir Zaman Alametleri, 496) “DÜŞMANLIK VE KİNİ DE KALDIRACAKTIR. Zehirli olan her hayvanın zehri de sökülüp alınacaktır. Hatta küçük oğlan çocuğu, elini yılanın ağzına sokacak da yılan ona zarar vermeyecektir. Kurt, koyun-keçi sürüsü içinde sürünün köpeği gibi olacaktır.” (Sünen-i İbni Mace, Kitabü-l fiten Tercemesi ve Şerhi- Kahraman Neşriyat, cilt 10, Mütercim: Haydar Hatipoğlu, Bab 33, sf. 331-335) “ONUN ZAMANINDA KURTLA KOYUN BİRARADA OYNAYACAK, YILANLAR ÇOCUKLARA ZARAR VERMEYECEKTİR. İnsan bir avuç tohum atacak, 700 avuç hasat edecektir.” (El Kavlu’l Muhtasar Fi Alamatil Mehdiyy-il Muntazar, sf. 43)
Sayın Adnan Oktar 27 Eylül 2010 tarihli Adıyaman Asu TV röportajında Hz. Mehdi (a.s.) zamanında silahların eritilip silahın kalmayacağını şöyle açıklamıştır:

ADNAN OKTAR: Bunu Peygamber (s.a.v.) söylüyor. Peygamberimiz (s.a.v.) vahiy ile söylüyor. Bunlar, ne diyor bu kancılar? “Biz Allah’tan da daha iyi biliyoruz. Allah’ın Peygamberi (s.a.v.)’nden iyi biliyoruz, Hz. Mehdi (a.s.)’dan da iyi biliyoruz” diyorlar haşa. “Kostantiniye feth olunur” diyor. Orada da yine tekbirlerle, Allah anılarak, inşaAllah. Çok fazla hadis var; İstanbul’un kan akıtılmadan, Allah anılarak alınacağına dair Peygamberimiz (s.a.v.)’in hadisleri meşhur. Şimdi bak, yobaz takımı bunu bir iyice anlayacak. Yani bu kan işinden, irin işinden bir vazgeçecekler. Bu konuda onları zannediyorum ikna edeceğiz, inşaAllah. Bakın şimdi yeniden tekrar ediyorum. “O Hz. Mehdi (a.s.) insanlığı sever. O insanlığın dostudur, o öldürmeye karşıdır. Öldürme yok. O ayırımcılığa karşıdır.” Kürt, Laz, Çerkez, Alevi, Sünni, Vahhabi; ayırımcılık yok, “ayırımcılığa karşıdır.” “O yoksulluğa karşı çıkacak.” Herkes zengin oluyor, fakir yok. Çünkü silahlanmaya ayrılan parayı fakirlere dağıtıyor. Silah yapımı yok. Mesela koskoca obüs topları, tanklar çelik yığını. Dünyanın yüz yıllık çelik ihtiyacını karşılayacak durumda şu an, silahlardaki demir. Bir kere demir zibil gibi olacak. Zaten Zülkarneyn Kıssası’nda ondan dikkat çekilmiştir. Demirin sel gibi akıtılacağı Kuran’da geçer, sel gibi akıtılacağı. Sel gibi demir akıtılacak. Bütün o tanklar, toplar hepsi eritilecek. Dolayısı ile silah kalmıyor. Silah kalmayınca kan nasıl aksın? Hz. İsa (a.s.) için ne diyor Peygamberimiz (s.a.v.)? “Bütün silahları yok edecek” diyor. Hz. İsa (a.s.) için. Hz. Mehdi (a.s.) için ne diyor? “Bütün silahları yok edecek” diyor. Silah niye yok edilir? Kan akmaması için, değil mi? Kancılar ne diyor? “Biz kan istiyoruz” diyorlar, vampirler, kancı vampirler. Kan, irin yok. Cehennemde bulacaklar, var onlara, Cehennemde irin var. Onun içinde yüzecekler meraklılarsa. Madem öyle irin meraklısı, kan meraklıları değil mi? Allah diyor ayette, Kuran’da var. Böyle irin denizinde, irin gölünde yüzecekler. O arzuları orada tam tatmin olmuş oluyor, Allah’ın dediğini haşa beğenmiyorlarsa eğer, tevbe edip vazgeçmezlerse, inşaAllah...

Hz. Mehdi (a.s.) Dünyaya Huzur ve Güven Getirecektir
Hadislerin işaretlerine göre Hz. Mehdi (a.s.)’ın manevi liderliğinde dünyaya barış ve esenlik gelecektir. Dünyadan anarşinin, terörün, kargaşanın, düşmanlığın, şiddetin tümüyle kalkması sonucunda insanlar cennet benzeri bir ortama kavuşacaklardır. Her türlü adil sistem oluşturulduğu ve tüm insanlar Allah korkusunu öğrendiği ve bunun şuuruna vardığı için hırsızlık, sahtekarlık, dolandırıcılık gibi toplumsal sorunlar yaşanmayacaktır. Cinayetler, saldırılar, taciz, iftira ve hakaret içeren eylemler ve toplum huzurunu bozacak her türlü tavır bozuklukları ve suistimaller ortadan kalkacaktır. Kavgalar, bağırtılar, tartışmalar, uyuşturucu almış insanların veya dengesiz insanların saldırma ihtimali son bulacak, insanlar bu tür eylemlerden kaynaklanan tüm endişe ve korkularından kurtulacaklardır. Peygamber Efendimiz (s.a.v.) Hz. Mehdi (a.s.) vesilesiyle dünyaya hakim olacak huzur ve güven ortamını şöyle anlatmaktadır:

“DAHA ÖNCE ZULÜMLE DOLU OLAN DÜNYAYI, ADALETLE DOLDURUR. ADALETİ O DENLİ OLUR Kİ, UYKUDA OLAN BİR KİMSE DAHİ UYANDIRILMAZ VE BİR DAMLA KAN BİLE AKITILMAZ. Dünya, adeta Asr-ı Saadet devrine geri döner.” (Nuaym b. Hammad, K. Fiten vr. 77b; Suyuti, c. II, sf. 77; El Kavlu’l Muhtasar Fi Alamatil Mehdiyy-il Muntazar, sf. 29)
Sayın Adnan Oktar 24 Ocak 2011 tarihli Kahramanmaraş Aksu TV röportajında, Allah’tan savaş istenmeyeceğini Allah’tan barış isteneceğini, bu duanın dünyaya huzur ve güvenlik vereceğini şöyle anlatmıştır:

ADNAN OKTAR: Allah savaşı beğenmez; Allah barışı beğenir. Allah sevgiyi, güzelliği beğenir, kardeşliği beğenir Allah, dostluğu beğenir. Savaş Allah vermesin, adam hiçbir şekilde laf söz dinlemez, saldırır; çar naçar kalırsın. Nefsi müdafaa. Zaten Allah seni orada başarılı kılar, yenersin o zaman. Mutlaka yenersin. İsterse atom bombası kullansın, isterse bilmem ne yapsın. Her ne yaparsa yapsın yenersin mazlumsan. Ama durduk yere millete saldırmak, insanlara saldırmak Müslümanın yapacağı bir şey değildir. Fitne çıkartıp, olay çıkartıp, kavga çıkartmak, savaş çıkartmak; bunlar densiz hareketlerdir. Bunları istemek de densizliktir. İran’la biz niye savaşalım kardeşim? Bilakis ittifak edeceğiz ve ediyoruz. Mehdi (a.s.) aşığıdır onlar. Yunanistan; Osmanlı döneminde evlatlarımızdı onlar bizim. Yine bizim yed-i emanımız olacaklardır.

Dolayısıyla ucuz kahramanlık yapıp böyle Müslümanlar arasında itibar kazanmak isteyenlere kardeşlerimiz itibar etmesinler. Dostluk, sevgi, merhamet, affedicilik, şefkat; Allah bunları beğenir. Cennette savaş yok, cennette kan yok, cennette kavga yok. Biz dünyayı cennet gibi yapacağız inşaAllah. Kanla, irinle Müslümanın işi olmaz. Allah’tan savaş istenmez. Allah’tan barış istenir.

Hz. Mehdi (a.s.) Sevgi ve Kardeşliğin Hakim Olmasına Vesile Olacaktır

“Allah bizimle insanları nasıl şirk adavetinden kurtararak, onların kalplerine ülfet ve muhabbet yerleştirmiş ve din kardeşi yapmışsa, HZ. MEHDİ (A.S.) İLE FİTNE ADAVETİNDEN KURTARACAK VE KARDEŞ YAPACAKTIR.” (Taberani’den, Heysemi, c. Vıı, sf. 317; Nuaym b. Hammad, vr 52b; Kitab-Ül Burhan Fi Alamet-İl Mehdiyy-İl Ahir Zaman, sf. 20) “Benim evladımdan Muhammed b. Abdullah (Mehdi) ile Cenab-ı Hak sünnetleri ihya eder. Onun adalet ve bereketi ile müminlerin kalpleri ferahlar. ACEM VE ARAP MİLLETLERİ ARASINDA ÜLFET VE MUHABBET YERLEŞİR.” (Kitab-ül Burhan Fi Alamet-İl Mehdiyy-İl Ahir Zaman, sf. 66)
Sayın Adnan Oktar 31 Mart 2011 tarihli A9 TV ve Samsun Aks TV röportajında barışın önemine şöyle dikkat çekmiştir:

ADNAN OKTAR: Barış önemli. Bakın, Tevrat’ta da barış anlatılır; “Ne iyi, ne güzeldir birlik içinde kardeşçe yaşamak.” Mezmurlar’da 133/1. “Bütün kralları Süleyman yönetiyordu. Her tarafta barış vardı.” Bakın; “bütün krallıkları Süleyman yönetiyordu.” Bir tek kendi ülkesini değil, diğer ülkelerin siyasetine de hakim olmuş. Bir İslam Birliği oluşmuş, İttihad-ı İslam oluşmuş o dönemde. “Bütün krallıkları Süleyman yönetiyordu.” Hz. Mehdi (a.s.)’ın da yapacağı budur. Bütün yönetimler manen ona bağlı olacaktır. “Her tarafta barış vardı” Peygamberimiz (s.a.v.), Hz. Mehdi (a.s.)’ı Hz. Süleyman (a.s.)’a benzetiyor. Hadiste Hz. Süleyman (a.s.) gibi olduğunu söylüyor. Burada da 1. Krallar 4. Bölüm, 24’te de; Hz. Süleyman (a.s.)’ın bütün krallıkları yönettiği, her tarafta da barış olduğu söyleniyor. “Kötülük tasarlayanların yüreği hileci; barışı öğütleyenin yüreği ise sevinçlidir.” Kötülük tasarlayan insanın yüreği rahat olmaz. Sürekli tedirgindir. Konuşmada dengesizlik, üslubunda tutarsızlıklar olur, anormallikler olur. Hilecidir, yani hileci olduğu hissedilir; insanlar sevemez, anlarlar onu. “Barışı öğütleyenin yüreği ise sevinçlidir.” Bak, “barışı öğütleyenin yüreği sevinçli,” çünkü içi rahat, kan istemiyor, kavga istemiyor. Kavga, kan isteyenler; onların tipi bile değişik olur, eşkali bozuk olur onların, üslubundan falan hissedilir. Kadın olsun, erkek olsun kan isteyenler daha mafyamsı, daha çirkin bir ruh halinde ve yüz ifadesinde olurlar. Ama bu dünyada çok yaygındır; kanı, kavgayı isteyenler çok çok fazladır. Barışı isteyen çok az insan vardır. Barış en kolayıdır ama çok az insan barışı ister. İnsanlar hep kavgayı isterler, büyük bölümü öyledir. Mesela biz anlatıyoruz, “Olur mu ya tabii ki barışı isteyenler çok olur” diyorlar, öyle bir şey olmuyor. Kavgayı ve savaşı isteyen çoktur dünyada. “Barışı öğütleyenin yüreği ise sevinçlidir.” Çünkü vicdanı rahat. Vicdanı rahat olduğu için kalbinde bir sıkıntı olmuyor. Ruhu gevşemiş. İnsancıl olduğunu biliyor, insanlara kötülük yapmayacağını biliyor. Kafasından bir kötülük tasarlamadığı için beyni kirlenmemiş ve vicdanı ona baskı yapmıyor, vicdan azabı çekmiyor.

Hz. Mehdi (a.s.)’ın Sevgisi ve Şefkati Tüm Dünyayı Kaplayacak, Herkes Ondan Memnun Olacaktır
Hz. Mehdi (a.s.) sevgi ve şefkat insanıdır. Allah’ın Hz. Mehdi (a.s.)’ın ruhunda yarattığı yoğun sevgi ve şefkatin, dünyanın her köşesine etki edeceği ve çok hayırlı bir dönem olacağı hadislerde şu şekilde ifade edilmektedir:

“İmam-ı zaman (Hz. Mehdi (a.s.))’ın bereketiyle İNSANLARIN KALPLERİ KARŞILIKLI SEVGİ VE BİRLİKLE DOLACAKTIR.” (Bihar-ul Envar, cilt 53, sayfa 187; Mikyaal al-makaarem, cilt 1, sayfa 52) “(Hz. Mehdi (a.s.) zamanında) SEVGİ VE ŞEFKAT DÜNYANIN KÖŞE BUCAK HER YERİNE HAKİM OLACAKTIR.” (İkbal’ul-a’mal sayfa 507; Bihar-ul Envar, cilt 21, sayfa 312) “Böylece YER VE GÖK SAKİNLERİ ONDAN (HZ. MEHDİ (AS)) RAZI OLDUKLARI GİBİ, HAVADAKİ KUŞLAR, ORMANDAKİ YIRTICI HAYVANLAR, DENİZDEKİ BALIKLAR BİLE MEMNUNLUK DUYACAKLARDIR. Ümmeti Muhammed’den (s.a.v.) memnun olmadık hiç kimse kalmayacaktır. Hatta, ‘ihtiyacı olan yok mu?’ diye tellal bağırtacak; ‘İhtiyacımız yoktur’ cevabı verilecektir.” (Medineli Allame Muhammed b. Resul el-Hüseyni el-Berzenci, Pamuk Yayıncılık, İstanbul, 2002, s. 163)
Yüce Allah, Kuran ahlakına uyan Müslümanlara cennet hayatlarında sunulacak olan güzellikleri ayetlerinde ayrıntılı olarak tarif etmiştir. Altından ırmaklar akan güzel mekanlar, pınarlar, durmaksızın akan kaynaklar, konaklar, köşkler, kıyafetler, yiyecekler, içecekler, mücevherler, güzel ahlaklarına karşılık sonsuz hayatta onlara verilecektir. Cennet Müslümanların her zaman kavuşmayı istedikleri sonsuz yaşamdır:

“Siz ve eşleriniz cennete girin; ‘sevinç içinde ağırlanacaksınız. Onların etrafında altın tepsiler ve testilerle dolaşılır; orada nefislerin arzu ettiği ve gözlerin lezzet (zevk) aldığı herşey var. Ve siz orada süresiz kalacaksınız. İşte, yaptıklarınız dolayısıyla mirasçı kılındığınız cennet budur. Orda sizin için birçok meyveler vardır; onlardan yiyeceksiniz.” (Zuhruf Suresi, 70-73)
İşte Hz. Mehdi (a.s.) tüm Müslümanlara böyle güzel bir hayatın dünyada hazırlanıp sunulmasında vesile olan değerli bir zattır. Hz. Mehdi (a.s.)’ın manevi liderliğinde oluşturulan ortam Peygamber Efendimiz (s.a.v.)’in müjdelediği gibi cennetin dünyadaki bir müjdesi, Allah’ın müminlere bir lütfudur. Bolluğuyla, bereketiyle, insanlara sağlayacağı her türlü konforuyla, huzur ve barış dolu ortamıyla her Müslümanın ulaşmak isteyeceği bu dönem, iman eden insanlar için dünya hayatında çok üstün bir mükafattır. Bu güzel dönemle müjdelenmek de kuşkusuz tüm Müslümanlar için çok büyük bir şereftir.

Sayın Adnan Oktar 9 Mart 2011 Tarihli TV Kayseri ve Samsun Aks TV röportajında Hz. Mehdi (a.s.)’ın asıl görevinin sevgi, şefkat ve merhamet olduğunu şöyle anlatmıştır:
ADNAN OKTAR: ;“Hz. Mehdi (a.s.) siyasete karışmaz” diyor. Hz. Mehdi (a.s.)’ın asıl görevi sevgi, şefkat ve merhamettir, ama sevgi siyasette etki eder. Nasıl etki eder? Dürüst siyaseti getirir, akılcı siyaseti getirir, merhametli siyaseti getirir. Mahkemeye etkisi olur. Dürüstleşir mahkemeler. Daha mükemmel, daha iyi olur. Daha sevgi dolu olur. Ticarete etkisi olur. Ticarete dürüstlük gelir, ticaret daha candan olur. Bu anlamdadır siyaset. Yoksa rejimleri değiştirmek, sistemleri değiştirmek, Hz. Mehdi (a.s.)’ın öyle bir görevi yok. Hz. Mehdi (a.s.)’ın görevi, güzel ahlakı, sevgiyi vermektir; şefkati, merhameti öğretmektir. Mesela acımasızlık varsa bir siyasetçide, o acımasızlık gider, sevgi hakim olur kalbine, merhametle bakar. Mesela eğer bir siyasetçi çıkar peşindeyse, Allah’tan korkup çıkar peşinde olmaz. Güzel ahlaklı olacağı için, bütün imkanlarını halka haşreder. Bu anlamda siyasete etkisi olur Hz. Mehdi (a.s.)’ın, doğrudan siyasetin içinde olmaz. Rejimleri değiştirmek, siyasete girmek, böyle bir sorunu yok Hz. Mehdi (a.s.)’ın. Çünkü dinde sorgulama yoktur, insanlar istedikleri inanç içerisinde olurlar, inşaAllah.

Hz. Mehdi (a.s.) Zamanında Farklı Dinler Arasında Barış ve Adalet Olacaktır
İslam dini, insanları dini inançlarını seçmede özgür bırakırken, diğer dinlere saygılı olmayı emreder. Bir insan Kuran’da batıl olarak tarif edilen bir inanca sahip olsa dahi, Kuran ahlakını yaşayan insanlar arasında huzur ve barış içinde yaşayabilir. Kendi inançlarına göre ibadetlerini özgürce yerine getirebilir. Hiç kimse bir diğerini kendi dininin ibadetlerini yerine getirmekten alıkoyamaz. Ya da bir insanı istediği şekilde ibadet etmeye zorlayamaz. Bu İslam ahlakına aykırıdır ve Allah’ın razı olmadığı bir davranış biçimidir. İslam tarihini incelediğimizde Peygamberimiz (s.a.v.)’in döneminde de herkesin özgürce ibadet edebildiği, inançlarının gereklerini yerine getirebildiği bir toplum modelinin hakim olduğu görülmektedir. Kuran’da Ehl-i Kitap’ın ibadet yerleri olan manastır, kilise ve havraların da Allah’ın koruduğu ibadet mekanları olduğu haber verilmektedir:

“... Eğer Allah’ın, insanların kimini kimiyle defetmesi olmasaydı, manastırlar, kiliseler, havralar ve içinde Allah’ın isminin çokça anıldığı mescidler, muhakkak yıkılır giderdi. Allah Kendi (dini)ne yardım edenlere kesin olarak yardım eder. Şüphesiz Allah, güçlü olandır, aziz olandır.” (Hac Suresi, 40)
Peygamberimiz (s.a.v.)’in hayatında bu ahlakın pek çok örneğine rastlanmaktadır. Peygamberimiz (s.a.v.), kendisiyle görüşmeye gelen Hristiyanların kendi mescidinde ibadet etmelerini söylemiş ve bu iş için mescidi onların kullanımına bırakmıştır. (Ali Bulaç, Çağdaş Kavramlar ve Düzenler, İz Yayıncılık, 16. Baskı, İstanbul, 1998, s. 241) Peygamberimiz (s.a.v.)’den sonraki halifeler devrinde de bu adaletli anlayış korunmuştur. Şam fethedildiği zaman, camiye çevrilen bir kilise ikiye bölünmüş, bir yarısında Hristiyanlar, öbür yarısında Müslümanlar ibadet etmişlerdir. (Ali Bulaç, Çağdaş Kavramlar ve Düzenler, İz Yayıncılık, 16. Baskı, İstanbul, 1998, s. 241)

Hadislerde tüm halkların barış ve huzur içerisinde yaşadıkları Asr-ı Saadet dönemi gibi, Hz. Mehdi (a.s.) döneminde de aynı adalet anlayışının hakim olacağı bildirilmektedir. Bu bilgilere göre Müslümanlar ile Hristiyan alemi arasında karşılıklı hoşgörüye dayalı bir kardeşlik, şefkat ve merhamet anlayışı oluşacaktır. Hristiyanların ve Yahudilerin tüm ibadethaneleri, havralar, kiliseler ve vakıfları koruma altına alınacak, kilise açmak isteyenlere, dini inançları doğrultusunda talepte bulunanlara, ibadetlerini yerine getirmek isteyenlere imkan tanınacaktır. Tüm Hristiyanların ve Yahudilerin kendileri için kutsal sayılan topraklarında barış, huzur ve güvenlik içinde yaşamaları sağlanacak, her türlü sorun sevgi, saygı ve adalet anlayışıyla kolaylıkla halledilebilecek, tüm halklar birbirleriyle uyum ve dostluk içerisinde yaşamlarını sürdürebileceklerdir.
