---
layout: post
title:  "DNA'daki Olağanüstü Bilgi Saklama Kapasitesi"
author: jane
categories: [ Biyoloji ]
image: assets/images/book.png
tags: [hücre]
keywords: DNA, Bilgi, Saklama, Kapasite
comments: false
published: true
lang: tr
encoding: UTF-8
---

Günümüzde bilgi saklama alanında gerçekleştirilen teknolojik ilerlemeler şaşırtıcı düzeydedir. Bilgisayar hard diskleri, CD'ler, disketler, taşıma diskleri ve benzeri teknolojik ürünler her geçen gün daha gelişmiş ve daha kullanışlı halleriyle kullanıma sunulmaktadır. Bilgisayar şirketleri, minimum alanda maksimum bilgi zarar görmeden nasıl depolanır; bu bilgi, gerektiğinde depolandığı alandan en hızlı nasıl geri alınıp kullanılır gibi sorulara çözüm aramaktadırlar. Her ne kadar bir CD'ye ansiklopedilerce bilgi sığdırılabilse de, yine de bu CD elinizle taşıyabileceğiniz kadarlık bir hacme sahiptir. DNA'nın bilgiyi minyatürleştirme, diğer bir deyişle sıkıştırma yeteneği ise, günümüz teknolojisinin çok ötesinde, şaşırtıcı bir boyuttadır. Kıyaslayacak olursak, Los Angeles, Güney California Üniversitesi'nden Leonard Adleman'ın yaptığı hesaplamalara göre, sadece 1 gram DNA, bir trilyon CD'ye eş değer bilgi saklayabilmektedir. *(John Whitfield, "Physicists Plunder Life's Tool Chest", Nature, 24 Nisan 2003.)* Bu da bilginin, DNA üzerinde, bir CD'ye göre milyon kere milyon kez daha verimli saklandığını göstermektedir. *(Carl Wieland, "The Marvellous 'Message Molecule'", Creation, Eylül 1995, cilt. 17, no. 4, ss. 10–13; [New Scientist, 26 Kasım 1994, s. 17.])*

İnsan DNA'sının hacmi bir milimetre küpün üç milyarda biri kadar (3 x 10-9 mm3) küçüktür. *(Werner Gitt, The Wonder of Man, Christliche Literatur-Verbreitung e.V., Almanya, 1999, s. 75.)* G. G. Simpson'a göre, bugüne kadar yaşamış, gelmiş geçmiş her canlı türünün bütün özellikleri bilgi olarak DNA'ya yüklense, toplam DNA hacmi bir çay kaşığının, ancak küçük bir kısmını doldururdu. Hatta geriye şu ana kadar yazılmış bütün kitapları saklayabilecek kadar boşluk kalırdı. *(Michael Denton, Evolution: A Theory in Crisis, Burnett Books, London, 1985, s. 334; [G. G. Simpson, "The History of Life", Evolution of Life, University of Chicago Press, Chicago, 1960, s. 135.])*

Yeni bir teknoloji alanı oluşturan **"DNA bilgisayarı"nın** muciti Dr. Leonard Adleman ise, hücre ve DNA'daki mekanizma hakkında şunları söylemektedir:

Eğer hücrenin içine bakarsak kendi başımıza yapamayacağımız fevkalade makinalar görürüz. Bu muhteşem bir alet kutusudur. *(John Whitfield, "Physicists Plunder Life's Tool Chest", Nature, 24 Nisan 2003. )*

Ancak Darwinistlere göre, hücrenin içindeki on binlerce ciltlik kitaba eş değer dev bilgi bankası, sözde tesadüfler sonucu kendiliğinden oluşmuştur. Bir imkansızlığın üstüne hiç çekinmeksizin bir yenisini daha bina edebilen Darwinistlere göre, bir stadyumu dolduracak kadar büyük bir kütüphanenin bütün bilgileri, gözle görülmeyen bir boyuta yine tesadüf eseri zarar görmeden sıkıştırılmıştır. İşte Darwinistler böylesine bir imkansızlığı gözü kapalı savunmaktadırlar. Ancak ne hücre ne de onun bilgi bankası olan DNA, şuursuz atomların tesadüfi olarak biraraya gelmesiyle oluşamaz. Canlılıların en küçük parçaları dahi belli bir amaca yönelik olarak yaratılmıştır ve her biri tesadüflere olanak tanımayacak kadar kompleks yapılardır. Sidney Üniversitesi'nden biyoloji profesörü Michael George Pitman, hayatın sadece cansız maddelerin toplamı olmadığını, Alman filozof Schoepenhauer'in şu ifadeleriyle dile getirmektedir:

... Her organizma tüm parçaları boyunca canlıdır ve bunlar hiçbir yerde -en küçük parçacıklarında dahi- sadece cansız maddelerin bir toplamı değildir. *(Michael Pitman, Adam and Evolution, River Publishing, London, 1984, ss. 26-27.)*

DNA'daki bilgi hacmini sayısal olarak ifade edecek olursak, 3-5 mikron (mikron: milimetrenin binde biri) çapındaki bir hücre içine, toplam 4 metre uzunluğundaki DNA molekülü sıkıştırılmış olarak paketlenmiştir. 100 trilyon hücrenin her birindeki DNA kodları art arda getirildiğinde ise, ortaya çıkan uzunluk, Güneş'e 600 kez gidiş-dönüş mesafesine eşittir. *(http://www.ntvmsnbc.com/news/13800.asp)* Bilimsel makaleleri ile tanınan moleküler biyolog Prof. Jerry Bergman, verdiği bir örnekte DNA'daki mühendisliği şöyle vurgulamaktadır:

Sizden 230 kilometre uzunlukta iki ayrı misina almanızı, bunu çifte sarmal haline getirmenizi ve sonra da bir basketbol topunun içerisine sığacak biçimde paketlemenizi istediklerini varsayın. Ayrıca, bu çifte sarmalın fermuar gibi açılıp kopyalanması gereksin... sonra kopyalanan parça dışarı çıkartılsın ve bu sırada misinalar kesinlikle birbirlerine karışmasın. Bu mümkün mü? Bu her gün vücudunuzdaki milyarlarca hücrede gerçekleşmektedir. Basketbol topunu insan hücresi boyutuna indirdiğinizde, ip de iki metreye yakın bir DNA zincirine dönüşecektir... DNA paketleme işlemi, hem kompleks ve hassas bir süreçtir hem de DNA'nın uzunluğunu 1 milyon kat azaltabilmeyi başardığı için son derece verimlidir. *(Dr. Jerry Bergman, “Divine Engineering: Unraveling DNA's Design”, Koinonia House Online; http://www.khouse.org/articles/technical/19971201-143.html)*

Moleküler biyolog Michael Denton ise DNA'nın bilgiyi sıkıştırma kapasitesindeki olağanüstülüğünü şu sözlerle dile getirmektedir:

... Hücrelerin aşırı derecede kompleks varlıklar oldukları açıktır. Hücredeki komplekslik bir jumbo jette bulunandan çok daha fazladır... sanki jumbo jetteki komplekslik insan gözünün göremeyeceği bir toz zerresine paketlenmiştir. Bu kadar kompleks olan bir şeyin, bu kadar küçük bir hacme nasıl sığdırıldığını anlamak çok zordur. Üstelik zerre büyüklüğünde bu jumbo jet, hiçbir çaba sarf etmeden kendisini çoğaltabilmektedir. *(Michael J. Denton, Nature's Destiny, Free Press, New York, 1998, ss. 212-213.)*

DNA'nın bilgi saklama yeteneği o kadar verimlidir ki, bir insana ait tüm bilgiler, yalnızca bir gramın birkaç trilyonda biri kadar yere sığabilmektedir. (Michael J. Denton, Nature's Destiny, Free Press, New York, 1998, s. 154.) Yale Üniversitesi'nden Prof. George Gaylord Simpson'a göre, yeryüzünde gelmiş geçmiş 1 milyar canlıya ait bilgi, kolaylıkla bir tuz taneciği içerisine sığdırılabilir.48 Ulusal İnsan Genomu Araştırma Enstitüsü yöneticisi, aynı zamanda fizikçi ve genetikçi olan Prof. Francis S. Collins ise DNA ile ilgili çalışmaları sonucunda şunları ifade etmektedir:

Watson ve Crick, DNA'nın çifte sarmal yapısını ortaya çıkarttıklarından bu yana elli sene geçti. Şimdi DNA üzerinde kayıtlı bilginin hassaslığı üzerinde düşünebilmek çok muhteşem... Bu dijital kod, insan vücudundaki her hücrede kolaylıkla kopyalanabilen, inanılmaz miktarda bilginin saklanmasına imkan tanıyor. Çifte sarmal şeklindeki DNA, baz çiftlerinden meydana geliyor ve hücre çekirdeğindeki insan genomu içerisinde bunlardan üç milyar tanesi paketlenmiş halde duruyor... Bu üç milyar harf insan vücudundaki tüm biyolojik özellikleri yönlendirebiliyor. *(Francis S. Collins, "Faith and the Human Genome Project", Perspectives on Science and Christian Faith, cilt.)*

Ünlü moleküler biyolog Michael Denton ise **"biyolojik bilginin, hücre çekirdeğinin minik hacmi içerisinde paketlenmesine imkan sağlayan, DNA'nın paketleme özelliklerinin"**, insan için özel olarak düzenlendiğini ifade etmektedir. *(Michael J. Denton, Nature's Destiny, Free Press, New York, 1998, s. 381.)* DNA, söz konusu sıkıştırma kapasitesine sahip olmasaydı, hücrenin, düzensiz DNA iplikçiklerini kapsayabilecek biçimde, çok daha büyük olması gerekecekti. Fakat hücrelerin daha büyük olmaları mümkün değildir. Çünkü hücrenin oksijen ve besin kaynakları, ancak hücrenin mevcut çapı kadar mesafede verimlidir. *(Michael J. Denton, Nature's Destiny, Free Press, New York, 1998, s. 154.)* Bu bakımdan hücrenin büyüklüğü, dolayısıyla DNA'nın sıkıştırma yeteneği, insan açısından hayati derecede önemlidir.

Bu muhteşem paketleme sistemi, DNA molekülünün, kıvrılma ve uzun sarmallar oluşturma yetenekleri sayesinde mümkün olmaktadır. Bu uzun sarmallar da, bükülerek iç içe geçmiş, düzenli sarmallar meydana getirirler. Böylece her hücrenin çekirdeğinde, ileri düzeyde bir mühendisliğe sahip paketleme teknolojisi görülür. Yüce Rabbimiz'in hücrelerimizde yarattığı bu paketleme sistemi ile, milyonlarca kilometrelik DNA harfi gözle göremediğimiz bir boyutta saklı durmaktadır.

### İnsan Hücresindeki Dev Ansiklopedi

DNA'da kayıtlı bulunan bilginin miktarı olağanüstüdür. Öyle ki, gözle görülmeyen tek bir DNA molekülünde, tam bir milyon ansiklopedi sayfasını dolduracak miktarda bilgi bulunur. Dikkat edin; tam 1.000.000 ansiklopedi sayfası... Diğer bir deyişle, her bir hücrenin çekirdeğinde, insan vücudunun işlevlerini kontrol etmeye yarayan, bir milyon sayfalık bilgi kodlanmıştır. Bu miktarı şöyle bir örnekle zihnimizde daha iyi canlandırabiliriz: Dünyanın en büyük ansiklopedilerinden birisi olan 23 ciltlik **"Encyclopedia Britannica"nın** bile toplam 25 bin sayfası vardır. Bu durumda, karşımıza olağanüstü bir tablo çıkar. Mikroskobik hücrenin içindeki, ondan çok daha küçük bir çekirdekte, milyonlarca bilgi içeren dünyanın en büyük ansiklopedisinin 40 katı büyüklüğünde bir bilgi deposu saklı durmaktadır. Bu da 920 ciltlik, dünyada eşi, benzeri olmayan dev bir ansiklopedi demektir. Yapılan tespitlere göre, bu dev ansiklopedi yaklaşık 5 milyar farklı bilgiye sahiptir. Bu son iki kelimeyi tekrarlayalım; **"bilgiye sahiptir"**...

İşte burada durup, ağzımızdan kolayca çıkan bu iki kelime üzerinde düşünmemiz gerekir. Bir hücrenin içinde milyarlarca bilgi olduğunu söylemek kolaydır. Ancak, burada sözünü ettiğimiz bir bilgisayar veya kütüphane değil, yalnızca protein, yağ ve su moleküllerinden oluşan, milimetreden 100 kat daha küçük bir alandır. Bu küçücük molekül kümesinin içinde, değil milyonlarca bilgi, tek bir bilginin muhafaza edilmesi bile son derece hayret verici bir mucizedir. Üstelik benzetme amacıyla kullanılan **"kitap"**, **"ansiklopedi"** gibi kavramlar bilgi saklayan, fakat cansız ve durgun kaynaklardır. İçindeki bilgilerin okunması ve talimatların yerine getirilmesi için bilinç sahibi birisine ihtiyaç vardır. Fakat DNA'dan bahsettiğimizde, sadece bilgi saklayan değil, bu bilgiyi kullanan, uygulayan canlı bir bilgi kaynağından bahsetmiş oluruz.

Gözle göremediğimiz, çapı milimetrenin milyarda biri büyüklüğünde olan, atomların yan yana dizilmesiyle oluşmuş bir zincir, böyle bir bilgiye ve hafızaya nasıl sahip olabilir? Bu soruya şunu da ekleyelim: Vücudunuzdaki 100 trilyon hücreden her biri bir milyon sayfayı ezbere biliyorken, acaba siz zeki ve şuurlu bir insan olarak hayatınız boyunca kaç ansiklopedi sayfası ezberleyebilirsiniz? Tüm bu sorular vicdan ve akıl sahibi herkesi, hücrenin üstün bir aklın, üstün bir ilmin eseri olduğu gerçeğine götürecektir. Evrimcilerin iddia ettiği gibi tesadüflerle, değil milyarlarca hücreden oluşan bir canlı, tek bir hücredeki DNA'nın dahi meydana gelmesi mümkün değildir.

<div class="embed-responsive embed-responsive-16by9">
<iframe allowfullscreen="" frameborder="0" height="270" src="https://www.youtube.com/embed/D16tCs9szhY" width="480"></iframe></div>
